### ISSUE TITLE
strange output in user manual

### ISSUE THREAD

**Issue by davidmatten** [philliplab/EpitopeMatcher#61]
In the file: EpitopeMatcher_manual.pdf
At the bottom of page 9: substitutionMatrix.
Included in the description are instances of: "`<e2><80><98>`"
![epitopematcher_issue](https://cloud.githubusercontent.com/assets/7010911/5009048/7a2b8398-6a6b-11e4-90d3-bfd18607efb9.jpg)

**Comment by philliplab** [comment]
migrated
